### ISSUE TITLE
Plugin breaks page styling

### ISSUE THREAD

**Issue by Tangol** [web-media/user_profile#3]
Please note that while testing this plugin, the page styling breaks when viewing the Public Profile (the view changes from List to Grid, the path appears as text on the page etc.).

![bug](https://user-images.githubusercontent.com/3336728/93145786-e2c1e600-f6f5-11ea-94e3-aadc2ba85706.jpg)

This shouldn't happen, as the plugin should have an effect only on the url routes and not directly on pages.

Osclass: 3.8.0
PHP: 7.0.33

**Comment by maddrid** [comment]
Hy .  This  plugin is   for  developers only  .  
As written in readme : "Example plugin to Bypass default osclass routing system " .
If you plan to use it in production , some additional checks has to be done
